### ISSUE TITLE
Ability to email / Notification

### ISSUE THREAD

**Issue by slitzer** [deck9/input#113]
First off, thanks for such a great app, so nicely poslished

Wanting to know if it would be within the scope of the project to add the ability to create either a email or even a Telegram notification when a form has been completed.

I can see there is an intergration aspect to Input, is there any documention around making this a posibiliy or am i dreaming XD

Again thanks 

Slitzer

**Comment by PhilReinking** [comment]
Hey @slitzer,

thank you for your warm words.

To your request, it should be possible right now to implement notifications with the integrations / webhook settings. I personally use a self-hosted instance of n8n to notify me on a chat application and to send me email notifications.

But I see that for something so simple like an email notification, it would be much easier to offer that by the app.

For something like Telegram, I think that is out of scope, since it would require extra credentials to setup, and I see this more in the integrations part of the software.

**Comment by dataprolet** [comment]
This is only somewhat related, but it would also be nice to be able to set a custom mail address per form to which the submissions are sent. This makes it possible to manage forms for other people that would still get mail notifications for submissions.
